import type { SpecularNodeInput, SpecularReferenceCandidate, SpecularScreenType } from '../specular-create/specular-types.js';

export type VanguardStackAdapter =
  | 'react-tailwind-shadcn'
  | 'vanilla-html-css-js'
  | 'vue'
  | 'svelte'
  | 'server-rendered-html';

export interface RetrobuilderVanguardPattern {
  id: string;
  title: string;
  sourcePromptName: string;
  category: string;
  screenTypes: SpecularScreenType[];
  intentTerms: string[];
  dependencies: string[];
  componentPath?: string;
  designDna: string[];
  implementationNotes: string[];
  mobileRules: string[];
  stackAdapters: Record<VanguardStackAdapter, string[]>;
}

export const RETROBUILDER_VANGUARD_DESIGN_DIRECTIVE = [
  'Retrobuilder vanguard design database:',
  '- Treat the selected vanguard patterns as the design contract, not decorative metadata.',
  '- Pick one primary signature pattern, one supporting interaction/text pattern, and one proof/action pattern when the screen allows it.',
  '- If the target stack supports React, Tailwind, TypeScript, and shadcn structure, implement the closest component directly under /components/ui or the project-equivalent UI folder.',
  '- If the stack does not support the exact component, translate the design intent: preserve composition, motion story, hierarchy, density, typography, and interaction behavior with the available technology.',
  '- Never fall back to generic dark glass, flat card piles, default dashboards, or debug/scaffold pages just because a dependency is unavailable.',
  '- Generated frontend must name the adapted pattern in internal notes/tests, but the visible UI must read like a real customer product.',
].join('\n');

const COMMON_STACK_ADAPTERS: Record<VanguardStackAdapter, string[]> = {
  'react-tailwind-shadcn': [
    'Use TypeScript components, Tailwind utilities, /components/ui when possible, and shadcn-compatible composition.',
    'Install only the dependencies required by the selected pattern and wire a real demo into the product screen.',
  ],
  'vanilla-html-css-js': [
    'Rebuild the composition with semantic HTML, CSS variables, CSS keyframes/transitions, IntersectionObserver, and small dependency-free JavaScript.',
    'Preserve the visual signature even when advanced component APIs are unavailable.',
  ],
  vue: [
    'Translate props and local state into Vue single-file components with scoped CSS or the project styling system.',
    'Use Vue transitions and composables to mimic the pattern motion.',
  ],
  svelte: [
    'Translate props/state into Svelte components with reactive declarations and scoped styles.',
    'Use Svelte transitions or CSS keyframes to preserve the motion rhythm.',
  ],
  'server-rendered-html': [
    'Render a static-first HTML product surface with CSS variables and progressive enhancement where JavaScript is available.',
    'Keep the same hierarchy, copy surfaces, and responsive behavior without requiring client-only APIs.',
  ],
};

type VanguardPatternBlueprint = {
  id: string;
  title: string;
  sourcePromptName: string;
  category: string;
  screenTypes: SpecularScreenType[];
  intentTerms: string[];
  dependencies: string[];
  componentPath?: string;
  signature: string;
  interaction: string;
  usage: string;
  fallback: string;
  contentRule?: string;
  mobile: string;
  mobileGuard: string;
};

function buildVanguardPattern(blueprint: VanguardPatternBlueprint): RetrobuilderVanguardPattern {
  return {
    id: blueprint.id,
    title: blueprint.title,
    sourcePromptName: blueprint.sourcePromptName,
    category: blueprint.category,
    screenTypes: blueprint.screenTypes,
    intentTerms: blueprint.intentTerms,
    dependencies: blueprint.dependencies,
    componentPath: blueprint.componentPath,
    designDna: [
      blueprint.signature,
      blueprint.interaction,
      blueprint.usage,
    ],
    implementationNotes: [
      blueprint.fallback,
      blueprint.contentRule || 'Replace demo labels, avatars, media, and copy with domain-specific product content.',
    ],
    mobileRules: [
      blueprint.mobile,
      blueprint.mobileGuard,
    ],
    stackAdapters: COMMON_STACK_ADAPTERS,
  };
}

export const RETROBUILDER_VANGUARD_PATTERNS: RetrobuilderVanguardPattern[] = [
  {
    id: 'container-scroll-animation',
    title: 'Cinematic Container Scroll',
    sourcePromptName: 'SCROLL ANIMATIONS',
    category: 'cinematic-scroll',
    screenTypes: ['landing', 'detail', 'dashboard'],
    intentTerms: ['scroll', 'hero', 'landing', 'showcase', 'product', 'preview', 'device', 'mockup'],
    dependencies: ['framer-motion'],
    componentPath: '/components/ui/container-scroll-animation.tsx',
    designDna: [
      'Oversized thesis headline above a perspective card.',
      'Scroll progress controls scale, rotation, and vertical translation.',
      'The card contains the real product preview, not an abstract placeholder image.',
    ],
    implementationNotes: [
      'Use for landing/product storytelling when one screen needs to feel premium immediately.',
      'Replace generic mockup imagery with domain-specific product screenshots, Unsplash photos, or rendered UI panels.',
    ],
    mobileRules: [
      'Reduce perspective depth and card scale below 768px.',
      'Keep headline lines short enough for 390px without horizontal scroll.',
    ],
    stackAdapters: COMMON_STACK_ADAPTERS,
  },
  {
    id: 'tilt-depth-cards',
    title: 'Tilt Depth Cards',
    sourcePromptName: 'TILT CARDS',
    category: 'interactive-card-depth',
    screenTypes: ['dashboard', 'list', 'detail', 'landing'],
    intentTerms: ['card', 'tilt', 'hover', 'depth', 'feature', 'pricing', 'product', 'catalog'],
    dependencies: ['framer-motion'],
    designDna: [
      'Cards react to cursor or focus with restrained perspective depth.',
      'Cards use tactile shadows, visible hierarchy, and one clear action per card.',
      'The interaction exists to clarify priority, not to decorate every panel.',
    ],
    implementationNotes: [
      'Use sparingly for high-value product cards, subscription packages, order options, or dashboard highlights.',
      'Fallback to focus/hover elevation and CSS transform when motion libraries are unavailable.',
    ],
    mobileRules: [
      'Disable pointer tilt on touch devices and keep tap states obvious.',
      'Avoid stacked cards wider than the viewport; use min-width:0 and wrapping safeguards.',
    ],
    stackAdapters: COMMON_STACK_ADAPTERS,
  },
  {
    id: 'hover-brand-logo',
    title: 'Hover Brand Proof Strip',
    sourcePromptName: 'leading companies',
    category: 'trust-proof',
    screenTypes: ['landing', 'detail', 'dashboard'],
    intentTerms: ['brand', 'logo', 'trust', 'proof', 'customer', 'company', 'partner', 'social'],
    dependencies: ['framer-motion', 'react-icons'],
    componentPath: '/components/ui/hover-brand-logo.tsx',
    designDna: [
      'A compact proof strip where hover changes the headline copy.',
      'Brand/icons are subdued until interaction reveals context.',
      'The section communicates credibility without becoming a logo dump.',
    ],
    implementationNotes: [
      'Adapt brand icons to real customer categories, partners, delivery channels, or integrations.',
      'For business apps, this can become a proof strip for WhatsApp, mobile web, Stripe, delivery, or CRM channels.',
    ],
    mobileRules: [
      'Use a small grid on mobile with large touch targets.',
      'Keep the proof label visible even without hover.',
    ],
    stackAdapters: COMMON_STACK_ADAPTERS,
  },
  {
    id: 'hero-scrub',
    title: 'Cinematic Hero Scrub',
    sourcePromptName: 'HERO SCRUB',
    category: 'scroll-scrubbed-hero',
    screenTypes: ['landing', 'detail'],
    intentTerms: ['hero', 'scrub', 'cinematic', 'frame', 'scroll', 'video', 'premium', 'brand'],
    dependencies: ['gsap'],
    componentPath: '/components/ui/hero-scrub.tsx',
    designDna: [
      'Full-screen sticky hero with frame-by-frame or simulated cinematic progression.',
      'Massive split title moves away as the product/brand visual becomes immersive.',
      'The scroll story creates a memorable first impression before the interface explains itself.',
    ],
    implementationNotes: [
      'Use when a brand, product, place, or service can be represented by strong visual atmosphere.',
      'If frame assets are unavailable, approximate with one high-quality image/video, CSS scale, and scroll progress.',
    ],
    mobileRules: [
      'Use safe viewport units and reduced scale on small screens.',
      'Respect prefers-reduced-motion and provide a static hero fallback.',
    ],
    stackAdapters: COMMON_STACK_ADAPTERS,
  },
  {
    id: 'prisma-video-hero',
    title: 'Prisma Editorial Video Hero',
    sourcePromptName: 'prisma-hero',
    category: 'editorial-video-hero',
    screenTypes: ['landing', 'detail'],
    intentTerms: ['video', 'hero', 'editorial', 'story', 'collective', 'brand', 'homepage'],
    dependencies: ['framer-motion', 'lucide-react'],
    componentPath: '/components/ui/prisma-hero.tsx',
    designDna: [
      'Edge-to-edge video or image background with editorial navigation and oversized type.',
      'Bottom-aligned content makes the brand feel cinematic and confident.',
      'A single rounded action button anchors the story.',
    ],
    implementationNotes: [
      'Adapt the nav labels, CTA, and story copy to the generated business instead of leaving portfolio language.',
      'Use a domain-relevant media asset; if none exists, use a high-quality gradient/photo treatment with noise.',
    ],
    mobileRules: [
      'Clamp title size aggressively and keep nav horizontally safe.',
      'Use overlay gradients to preserve text contrast.',
    ],
    stackAdapters: COMMON_STACK_ADAPTERS,
  },
  {
    id: 'marker-highlight',
    title: 'Animated Marker Highlight',
    sourcePromptName: 'MARKERS HIGHLIGHTS',
    category: 'text-emphasis-motion',
    screenTypes: ['landing', 'form', 'wizard', 'detail'],
    intentTerms: ['highlight', 'marker', 'copy', 'headline', 'builder', 'explain', 'emphasis'],
    dependencies: ['remotion', '@remotion/player'],
    componentPath: '/components/ui/marker-highlight.tsx',
    designDna: [
      'A marker swipe gives one keyword emotional weight.',
      'The highlight is simple, readable, and timed like a product statement.',
      'Best for one memorable promise, not paragraphs.',
    ],
    implementationNotes: [
      'If Remotion is too heavy for the target stack, implement with CSS keyframes and inline spans.',
      'Use domain words that matter: fresh bread, daily delivery, WhatsApp orders, monthly plans, verified care.',
    ],
    mobileRules: [
      'Keep line length short and avoid enormous fixed font sizes on mobile.',
      'Ensure highlighted text wraps cleanly.',
    ],
    stackAdapters: COMMON_STACK_ADAPTERS,
  },
  {
    id: 'grid-pixelate-wipe',
    title: 'Grid Pixelate Wipe',
    sourcePromptName: 'Grid Pixelate wipes',
    category: 'scene-transition',
    screenTypes: ['landing', 'dashboard', 'wizard'],
    intentTerms: ['transition', 'wipe', 'pixel', 'grid', 'scene', 'state', 'launch', 'arrive'],
    dependencies: ['remotion', '@remotion/player'],
    componentPath: '/components/ui/grid-pixelate-wipe.tsx',
    designDna: [
      'Scene transitions happen through a grid of cells instead of a bland fade.',
      'Useful for showing before/after, request-to-delivery, or setup-to-live states.',
      'The pattern brings motion craft to state changes.',
    ],
    implementationNotes: [
      'Use for onboarding, order status, or dashboard state transitions.',
      'Fallback with CSS grid cells and staggered opacity when Remotion is unavailable.',
    ],
    mobileRules: [
      'Reduce grid density on small screens.',
      'Keep content legible during transition; do not hide primary actions too long.',
    ],
    stackAdapters: COMMON_STACK_ADAPTERS,
  },
  {
    id: 'infinite-bento-pan',
    title: 'Infinite Bento Pan',
    sourcePromptName: 'INFINITE BENTO PAN',
    category: 'data-motion-bento',
    screenTypes: ['dashboard', 'landing', 'list'],
    intentTerms: ['bento', 'dashboard', 'metrics', 'analytics', 'cards', 'pan', 'data', 'status'],
    dependencies: ['remotion', '@remotion/player'],
    componentPath: '/components/ui/infinite-bento-pan.tsx',
    designDna: [
      'A large bento canvas pans through many meaningful modules.',
      'Each card has a role: chart, counter, stat, code, logo, gradient, or bars.',
      'The dashboard feels alive without becoming noisy.',
    ],
    implementationNotes: [
      'Translate cards into real domain modules: orders, customers, deliveries, WhatsApp queue, revenue, subscriptions.',
      'Fallback to CSS transform animation or a static bento overview when video/runtime APIs are not available.',
    ],
    mobileRules: [
      'Use a cropped viewport with readable cards instead of shrinking everything.',
      'Prefer one-column summary below the motion canvas for accessibility.',
    ],
    stackAdapters: COMMON_STACK_ADAPTERS,
  },
  {
    id: 'perspective-marquee',
    title: 'Perspective Marquee',
    sourcePromptName: 'PERSPECTIVE MARQUEEE',
    category: 'kinetic-proof',
    screenTypes: ['landing', 'dashboard', 'detail'],
    intentTerms: ['marquee', 'perspective', 'brands', 'channels', 'integrations', 'motion', 'proof'],
    dependencies: ['remotion', '@remotion/player'],
    componentPath: '/components/ui/remocn-perspective-marquee.tsx',
    designDna: [
      'A moving word/brand strip is rotated in perspective with fade and blur.',
      'The motion communicates scale, ecosystem, or operational breadth.',
      'It works best as ambient proof around a stronger hero.',
    ],
    implementationNotes: [
      'Use actual integrations, services, product categories, or delivery promises instead of random SaaS logos.',
      'Fallback to CSS marquee with transform/perspective when Remotion is unavailable.',
    ],
    mobileRules: [
      'Lower font size and speed on mobile.',
      'Keep important proof available in static text for reduced motion.',
    ],
    stackAdapters: COMMON_STACK_ADAPTERS,
  },
  {
    id: 'masked-slide-reveal',
    title: 'Masked Slide Reveal',
    sourcePromptName: 'REVEAL FROM THE MASK',
    category: 'text-reveal-motion',
    screenTypes: ['landing', 'form', 'wizard', 'detail', 'chat'],
    intentTerms: ['reveal', 'mask', 'headline', 'words', 'copy', 'stagger', 'motion'],
    dependencies: ['remotion', '@remotion/player'],
    componentPath: '/components/ui/masked-slide-reveal.tsx',
    designDna: [
      'Words reveal upward through a mask with staggered timing.',
      'This gives simple copy a crafted launch moment.',
      'It can introduce sections, empty states, onboarding steps, or premium CTAs.',
    ],
    implementationNotes: [
      'If Remotion is unavailable, use CSS overflow masks and staggered keyframes.',
      'Keep text short, domain-specific, and directly tied to the user goal.',
    ],
    mobileRules: [
      'Use clamp() font sizes and line-height around 1.',
      'Avoid long unrecoverable single-line words.',
    ],
    stackAdapters: COMMON_STACK_ADAPTERS,
  },
  buildVanguardPattern({
    id: 'motion-footer',
    title: 'Motion Footer Link Field',
    sourcePromptName: 'Motion Footer',
    category: 'footer-navigation-motion',
    screenTypes: ['landing', 'detail', 'dashboard'],
    intentTerms: ['footer', 'links', 'navigation', 'motion', 'credits', 'brand'],
    dependencies: ['motion', 'lucide-react'],
    componentPath: '/components/ui/motion-footer.tsx',
    signature: 'A footer becomes a tactile destination with animated link fields and branded closing rhythm.',
    interaction: 'Hover and focus states reveal motion rather than flat underlines.',
    usage: 'Best for landing pages and product surfaces that need a memorable final section.',
    fallback: 'Use CSS transform, underline masks, and staggered opacity when motion/react is unavailable.',
    mobile: 'Collapse footer groups into stacked sections with full-width tap targets.',
    mobileGuard: 'Keep legal, contact, and primary CTA links visible without horizontal scrolling.',
  }),
  buildVanguardPattern({
    id: 'interfaces-breadcrumb',
    title: 'Interface Breadcrumb Trail',
    sourcePromptName: 'Interfaces Breadcrumb',
    category: 'navigation-context',
    screenTypes: ['dashboard', 'detail', 'form', 'wizard'],
    intentTerms: ['breadcrumb', 'navigation', 'trail', 'path', 'settings', 'account'],
    dependencies: ['lucide-react'],
    componentPath: '/components/ui/interfaces-breadcrumb.tsx',
    signature: 'A compact breadcrumb gives operational context without stealing vertical space.',
    interaction: 'Segments use icon affordances, truncation, and clear current-state contrast.',
    usage: 'Use for settings, detail records, checkout flows, and builder step context.',
    fallback: 'Use semantic nav/ol markup with CSS separators and current-page aria attributes.',
    mobile: 'Collapse middle crumbs into an overflow segment under 390px.',
    mobileGuard: 'Ensure the final crumb wraps or truncates cleanly with min-width:0.',
  }),
  buildVanguardPattern({
    id: 'interfaces-slider',
    title: 'Interface Slider Control',
    sourcePromptName: 'Interfaces Slider',
    category: 'input-control',
    screenTypes: ['form', 'dashboard', 'wizard'],
    intentTerms: ['slider', 'range', 'amount', 'volume', 'settings', 'control', 'pricing'],
    dependencies: ['@radix-ui/react-slider', 'lucide-react'],
    componentPath: '/components/ui/interfaces-slider.tsx',
    signature: 'A range control feels precise, labeled, and connected to live value feedback.',
    interaction: 'Thumb, track, and labels make numeric adjustment understandable at a glance.',
    usage: 'Use for budgets, quantities, delivery windows, model temperature, media volume, or plan limits.',
    fallback: 'Use native input[type=range] with CSS variables and a synchronized output label.',
    mobile: 'Increase hit area to at least 44px and keep labels below the thumb path.',
    mobileGuard: 'Do not let long labels overlap the track or current value.',
  }),
  buildVanguardPattern({
    id: 'cobe-globe',
    title: 'COBE Global Presence Globe',
    sourcePromptName: 'COBE Globe',
    category: 'geo-visualization',
    screenTypes: ['landing', 'dashboard', 'detail'],
    intentTerms: ['globe', 'map', 'global', 'world', 'locations', 'presence', 'network'],
    dependencies: ['cobe', 'react'],
    componentPath: '/components/ui/cobe-globe.tsx',
    signature: 'A live globe anchors global reach with pins and subtle rotation.',
    interaction: 'Pointer drag, auto-rotation, and markers create a premium spatial proof moment.',
    usage: 'Use for shipping coverage, data centers, customer distribution, travel, or market reach.',
    fallback: 'Use a CSS radial globe, SVG map, or static world map with animated pins when WebGL/canvas is unavailable.',
    mobile: 'Reduce globe size and pin density while preserving the main coverage story.',
    mobileGuard: 'Provide a text/list fallback for locations below the canvas.',
  }),
  buildVanguardPattern({
    id: 'cobe-globe-pulse',
    title: 'COBE Pulse Globe',
    sourcePromptName: 'COBE Globe Pulse',
    category: 'geo-signal-visualization',
    screenTypes: ['landing', 'dashboard'],
    intentTerms: ['pulse', 'globe', 'signal', 'live', 'traffic', 'network', 'latency'],
    dependencies: ['cobe', 'react'],
    componentPath: '/components/ui/cobe-globe-pulse.tsx',
    signature: 'Pulsing arcs or markers make a global system feel alive in real time.',
    interaction: 'Animated pulses express traffic, incidents, delivery routes, or active users.',
    usage: 'Use when the product promise includes live coverage, monitoring, logistics, or distributed infrastructure.',
    fallback: 'Use SVG arcs with CSS keyframes or canvas dots if COBE is unavailable.',
    mobile: 'Show fewer simultaneous pulses and keep the focal marker centered.',
    mobileGuard: 'Avoid continuous heavy animation on low-power devices and support reduced motion.',
  }),
  buildVanguardPattern({
    id: 'base-ui-switch',
    title: 'Base UI Switch',
    sourcePromptName: 'Base UI Switch',
    category: 'binary-control',
    screenTypes: ['form', 'dashboard', 'wizard'],
    intentTerms: ['switch', 'toggle', 'setting', 'enabled', 'binary', 'preference'],
    dependencies: ['@base-ui/react'],
    componentPath: '/components/ui/base-ui-switch.tsx',
    signature: 'A compact switch uses a clear thumb, label, and state contrast instead of a checkbox substitute.',
    interaction: 'Keyboard, click, and focus states are first-class.',
    usage: 'Use for notification preferences, feature flags, privacy states, or plan options.',
    fallback: 'Use a semantic button or checkbox with aria-checked and CSS transform states.',
    mobile: 'Keep the switch and label in one readable row with a 44px touch area.',
    mobileGuard: 'Never rely on color alone to communicate on/off state.',
  }),
  buildVanguardPattern({
    id: 'interfaces-table',
    title: 'Dense Interface Table',
    sourcePromptName: 'Interfaces Table',
    category: 'data-table',
    screenTypes: ['dashboard', 'list'],
    intentTerms: ['table', 'rows', 'data', 'records', 'orders', 'customers', 'ledger', 'inventory'],
    dependencies: ['lucide-react'],
    componentPath: '/components/ui/interfaces-table.tsx',
    signature: 'A table reads like a real operations surface with density, row actions, status, and sortable context.',
    interaction: 'Hover states, checkboxes, badges, and action menus support repeated work.',
    usage: 'Use for orders, customers, inventory, invoices, tasks, or audit logs.',
    fallback: 'Use semantic table markup with responsive row cards when advanced table libraries are unavailable.',
    mobile: 'Convert columns into labeled row cards or horizontal-safe priority columns.',
    mobileGuard: 'Preserve action buttons and status without clipping or requiring tiny text.',
  }),
  buildVanguardPattern({
    id: 'cobe-globe-polaroids',
    title: 'COBE Globe Polaroids',
    sourcePromptName: 'COBE Globe Polaroids',
    category: 'geo-storytelling',
    screenTypes: ['landing', 'detail'],
    intentTerms: ['globe', 'photos', 'polaroid', 'locations', 'travel', 'community', 'proof'],
    dependencies: ['cobe', 'framer-motion'],
    componentPath: '/components/ui/cobe-globe-polaroids.tsx',
    signature: 'A globe pairs with floating image cards to make locations feel human and specific.',
    interaction: 'Photos drift, stack, or reveal as the globe rotates.',
    usage: 'Use for travel, creator communities, logistics stories, venue portfolios, or city coverage.',
    fallback: 'Use static map imagery with layered photo cards and CSS transforms if COBE is unavailable.',
    mobile: 'Stack the photo cards below the globe and keep only one floating image active.',
    mobileGuard: 'Ensure images have fixed aspect ratios to avoid layout jumps.',
  }),
  buildVanguardPattern({
    id: 'cobe-globe-cdn',
    title: 'COBE CDN Edge Globe',
    sourcePromptName: 'COBE Globe CDN',
    category: 'infrastructure-visualization',
    screenTypes: ['landing', 'dashboard'],
    intentTerms: ['cdn', 'edge', 'latency', 'infrastructure', 'network', 'regions', 'global', 'dashboard'],
    dependencies: ['cobe', 'lucide-react'],
    componentPath: '/components/ui/cobe-globe-cdn.tsx',
    signature: 'A globe turns infrastructure into an understandable edge network with regions and latency cues.',
    interaction: 'Markers, arcs, and metric chips connect geography to performance.',
    usage: 'Use for hosting, observability, delivery networks, AI routing, or international operations.',
    fallback: 'Use SVG arcs, region cards, and animated latency chips when COBE is unavailable.',
    mobile: 'Summarize edge regions in cards below the visual.',
    mobileGuard: 'Keep metrics legible and avoid canvas covering the primary CTA.',
  }),
  buildVanguardPattern({
    id: 'background-parallax-hero',
    title: 'Background Parallax Hero',
    sourcePromptName: 'Background Parallax Hero',
    category: 'immersive-hero',
    screenTypes: ['landing', 'detail'],
    intentTerms: ['parallax', 'background', 'hero', 'image', 'depth', 'landing'],
    dependencies: ['framer-motion', 'lucide-react'],
    componentPath: '/components/ui/background-parallax-hero.tsx',
    signature: 'A full-bleed image scene shifts with scroll or pointer depth behind concise hero copy.',
    interaction: 'Parallax is restrained and tied to the subject, not decorative layers.',
    usage: 'Use for places, products, events, food, travel, and object-led pages.',
    fallback: 'Use CSS background-position, transform, and scroll-linked classes when motion APIs are unavailable.',
    mobile: 'Reduce parallax movement and crop the image around the subject.',
    mobileGuard: 'Always preserve text contrast with a gradient overlay.',
  }),
  buildVanguardPattern({
    id: 'cinematic-landing-hero',
    title: 'Cinematic Landing Hero',
    sourcePromptName: 'Cinematic Landing Hero',
    category: 'immersive-landing',
    screenTypes: ['landing'],
    intentTerms: ['cinematic', 'landing', 'hero', 'video', 'brand', 'launch', 'offer'],
    dependencies: ['lucide-react', 'framer-motion'],
    componentPath: '/components/ui/cinematic-landing-hero.tsx',
    signature: 'The first viewport feels like a composed film frame with one dominant message and real media.',
    interaction: 'Page-load reveals, CTA affordances, and image movement create a crafted opening.',
    usage: 'Use for premium services, portfolios, brands, venues, and product launches.',
    fallback: 'Use a full-bleed high-quality image and CSS keyframes when video or motion dependencies are unavailable.',
    mobile: 'Leave a hint of the next section visible and avoid carded hero layouts.',
    mobileGuard: 'Clamp headings and keep the brand/product visible in the first viewport.',
  }),
  buildVanguardPattern({
    id: 'base-ui-combobox',
    title: 'Base UI Combobox',
    sourcePromptName: 'Base UI Combobox',
    category: 'search-select-control',
    screenTypes: ['form', 'dashboard', 'wizard'],
    intentTerms: ['combobox', 'search', 'select', 'filter', 'command', 'picker', 'member'],
    dependencies: ['@base-ui/react', 'lucide-react'],
    componentPath: '/components/ui/base-ui-combobox.tsx',
    signature: 'Search and selection are merged into a keyboard-friendly popover control.',
    interaction: 'Filtering, highlighted rows, empty state, and chosen value are all explicit.',
    usage: 'Use for country, customer, plan, team member, category, or command selection.',
    fallback: 'Use input plus listbox semantics and native focus management when Base UI is unavailable.',
    mobile: 'Use full-width popovers or sheets when space is tight.',
    mobileGuard: 'Keep the focused option visible above the keyboard.',
  }),
  buildVanguardPattern({
    id: 'motion-volume-control',
    title: 'Motion Volume Control',
    sourcePromptName: 'Motion Volume Control',
    category: 'media-control',
    screenTypes: ['dashboard', 'detail', 'form'],
    intentTerms: ['volume', 'audio', 'media', 'slider', 'sound', 'control'],
    dependencies: ['motion', 'lucide-react'],
    componentPath: '/components/ui/motion-volume-control.tsx',
    signature: 'A volume surface combines icon state, slider feedback, and animated level changes.',
    interaction: 'Mute, drag, hover, and keyboard actions feel continuous.',
    usage: 'Use for media apps, calls, notification sounds, voice tools, or playback settings.',
    fallback: 'Use native range input and icon swaps with CSS transitions when motion is unavailable.',
    mobile: 'Make the slider track wide enough for thumb control.',
    mobileGuard: 'Provide visible mute state and aria labels for screen readers.',
  }),
  buildVanguardPattern({
    id: 'glass-blog-card',
    title: 'Glass Editorial Blog Card',
    sourcePromptName: 'Glass Blog Card',
    category: 'content-card',
    screenTypes: ['list', 'landing', 'detail'],
    intentTerms: ['blog', 'article', 'card', 'news', 'editorial', 'glass', 'content'],
    dependencies: ['lucide-react'],
    componentPath: '/components/ui/glass-blog-card.tsx',
    signature: 'An article card layers image, metadata, and glass treatment without becoming generic dark glass.',
    interaction: 'Hover reveals reading intent through image scale, metadata contrast, and CTA movement.',
    usage: 'Use for posts, case studies, changelogs, recipes, guides, or editorial collections.',
    fallback: 'Use plain CSS backdrop-filter or a solid card with the same image hierarchy.',
    mobile: 'Use stable image aspect ratios and stack metadata before title.',
    mobileGuard: 'Keep card text to a predictable number of lines to prevent uneven grids.',
  }),
  buildVanguardPattern({
    id: 'special-text-scramble',
    title: 'Special Text Scramble',
    sourcePromptName: 'Special Text Scramble',
    category: 'text-motion',
    screenTypes: ['landing', 'detail', 'chat', 'wizard'],
    intentTerms: ['scramble', 'text', 'headline', 'code', 'ai', 'terminal', 'reveal'],
    dependencies: ['framer-motion'],
    componentPath: '/components/ui/special-text-scramble.tsx',
    signature: 'Text resolves from scrambled glyphs into a clear promise or system state.',
    interaction: 'The reveal communicates computation, transformation, or unlock moments.',
    usage: 'Use for AI tools, security, builders, wait states, search, or premium headline moments.',
    fallback: 'Use requestAnimationFrame or CSS step animations when motion is unavailable.',
    mobile: 'Limit scrambled words to short strings and avoid shifting surrounding layout.',
    mobileGuard: 'Always render the final readable text in the DOM.',
  }),
  buildVanguardPattern({
    id: 'location-map',
    title: 'Location Map Card',
    sourcePromptName: 'Location Map',
    category: 'geo-card',
    screenTypes: ['detail', 'landing', 'dashboard'],
    intentTerms: ['location', 'map', 'address', 'directions', 'venue', 'delivery', 'branch'],
    dependencies: ['lucide-react'],
    componentPath: '/components/ui/location-map.tsx',
    signature: 'A location card combines map texture, address, directions, and local context.',
    interaction: 'Pins, route buttons, and hover states make the card actionable.',
    usage: 'Use for stores, venues, delivery coverage, field teams, or appointment locations.',
    fallback: 'Use a static map image or CSS grid map texture with a clear directions link.',
    mobile: 'Make directions and call actions large enough for thumb use.',
    mobileGuard: 'Do not let map media push address details below the fold on compact screens.',
  }),
  buildVanguardPattern({
    id: 'button-with-icon',
    title: 'Icon Button CTA',
    sourcePromptName: 'Button with Icon',
    category: 'action-button',
    screenTypes: ['landing', 'form', 'dashboard', 'detail', 'wizard'],
    intentTerms: ['button', 'icon', 'cta', 'action', 'submit', 'download', 'continue'],
    dependencies: ['lucide-react'],
    componentPath: '/components/ui/button-with-icon.tsx',
    signature: 'A CTA pairs concise text with an icon that clarifies the action.',
    interaction: 'Hover or press moves the icon subtly and confirms the command.',
    usage: 'Use for primary actions, downloads, booking, sending, saving, and navigation.',
    fallback: 'Use a native button or anchor with inline SVG/lucide equivalent where available.',
    mobile: 'Keep button height stable and text short.',
    mobileGuard: 'Icon and label must not wrap awkwardly or resize the button on hover.',
  }),
  buildVanguardPattern({
    id: 'team-member-card',
    title: 'Team Member Card',
    sourcePromptName: 'Team Member Card',
    category: 'profile-card',
    screenTypes: ['list', 'detail', 'dashboard', 'landing'],
    intentTerms: ['team', 'member', 'profile', 'avatar', 'role', 'people', 'staff'],
    dependencies: ['lucide-react'],
    componentPath: '/components/ui/team-member-card.tsx',
    signature: 'A member card presents avatar, role, contact, availability, and trust cues with restraint.',
    interaction: 'Hover or focus reveals contact/social actions without hiding identity.',
    usage: 'Use for teams, assignees, experts, staff, collaborators, or advisors.',
    fallback: 'Use semantic article cards with image fallback initials.',
    mobile: 'Use one-column cards or compact list rows depending on density.',
    mobileGuard: 'Ensure long names and roles truncate predictably.',
  }),
  buildVanguardPattern({
    id: 'bento-card-tabs',
    title: 'Bento Card Tabs',
    sourcePromptName: 'Bento Card Tabs',
    category: 'tabbed-bento',
    screenTypes: ['dashboard', 'landing', 'detail'],
    intentTerms: ['bento', 'tabs', 'features', 'modules', 'overview', 'cards'],
    dependencies: ['framer-motion', 'lucide-react'],
    componentPath: '/components/ui/bento-card-tabs.tsx',
    signature: 'Tabbed navigation changes a bento panel instead of swapping bland content blocks.',
    interaction: 'Active tabs animate layout and reveal different product modules.',
    usage: 'Use for feature overviews, settings groups, analytics modes, or plan comparisons.',
    fallback: 'Use CSS grid, buttons, and opacity transforms when motion is unavailable.',
    mobile: 'Make tabs horizontally scrollable or convert to segmented rows.',
    mobileGuard: 'Keep active content close to its tab and avoid nested cards.',
  }),
  buildVanguardPattern({
    id: 'framer-switch',
    title: 'Framer Animated Switch',
    sourcePromptName: 'Framer Switch',
    category: 'binary-control-motion',
    screenTypes: ['form', 'dashboard', 'wizard'],
    intentTerms: ['switch', 'framer', 'toggle', 'motion', 'setting', 'mode'],
    dependencies: ['framer-motion'],
    componentPath: '/components/ui/framer-switch.tsx',
    signature: 'A switch uses layout animation to make state changes feel physical.',
    interaction: 'Thumb movement, background, and optional icons animate together.',
    usage: 'Use for mode toggles, billing cadence, privacy, notifications, and feature flags.',
    fallback: 'Use CSS transitions on a semantic switch button when framer-motion is unavailable.',
    mobile: 'Keep the thumb movement short and touch target generous.',
    mobileGuard: 'State label must remain visible for accessibility and clarity.',
  }),
  buildVanguardPattern({
    id: 'vertical-tabs-gallery',
    title: 'Vertical Tabs Gallery',
    sourcePromptName: 'Vertical Tabs Gallery',
    category: 'gallery-navigation',
    screenTypes: ['landing', 'detail', 'dashboard'],
    intentTerms: ['vertical', 'tabs', 'gallery', 'image', 'features', 'portfolio'],
    dependencies: ['framer-motion', 'lucide-react'],
    componentPath: '/components/ui/vertical-tabs-gallery.tsx',
    signature: 'A vertical tab rail controls a visual gallery with strong image hierarchy.',
    interaction: 'Selecting a tab updates the hero image or panel with directional motion.',
    usage: 'Use for portfolios, services, product modes, recipes, properties, or venue spaces.',
    fallback: 'Use CSS transitions and static images with aria-selected tabs.',
    mobile: 'Convert vertical tabs into a horizontal strip above the image.',
    mobileGuard: 'Keep gallery media aspect ratio stable across tab changes.',
  }),
  buildVanguardPattern({
    id: 'text-roll',
    title: 'Text Roll',
    sourcePromptName: 'Text Roll',
    category: 'micro-text-motion',
    screenTypes: ['landing', 'dashboard', 'detail', 'chat'],
    intentTerms: ['text', 'roll', 'number', 'ticker', 'counter', 'status', 'label'],
    dependencies: ['framer-motion'],
    componentPath: '/components/ui/text-roll.tsx',
    signature: 'Text changes roll vertically like a ticker instead of snapping.',
    interaction: 'State changes, counters, or labels transition with readable momentum.',
    usage: 'Use for metrics, statuses, plan names, route names, or compact AI response states.',
    fallback: 'Use CSS translateY keyframes and overflow-hidden wrappers.',
    mobile: 'Limit rolling labels to short strings and reserve fixed width.',
    mobileGuard: 'Prevent layout shift by constraining the text container.',
  }),
  buildVanguardPattern({
    id: 'glass-account-settings-card',
    title: 'Glass Account Settings Card',
    sourcePromptName: 'Glass Account Settings Card',
    category: 'settings-surface',
    screenTypes: ['form', 'dashboard'],
    intentTerms: ['account', 'settings', 'profile', 'preferences', 'card', 'glass'],
    dependencies: ['lucide-react'],
    componentPath: '/components/ui/glass-account-settings-card.tsx',
    signature: 'Account settings are grouped into a polished card with real controls and account context.',
    interaction: 'Rows have toggles, edit actions, focus states, and clear save affordances.',
    usage: 'Use for profile, billing, preferences, security, and notification settings.',
    fallback: 'Use solid surface cards with subtle borders if backdrop-filter is unavailable.',
    mobile: 'Stack setting rows with labels above controls when space is narrow.',
    mobileGuard: 'Do not compress inputs or toggles into unreadable columns.',
  }),
  buildVanguardPattern({
    id: 'link-hover-image-preview',
    title: 'Link Hover Image Preview',
    sourcePromptName: 'Link Hover Image Preview',
    category: 'preview-interaction',
    screenTypes: ['landing', 'list', 'detail'],
    intentTerms: ['link', 'hover', 'preview', 'image', 'portfolio', 'menu', 'case'],
    dependencies: ['framer-motion'],
    componentPath: '/components/ui/link-hover-image-preview.tsx',
    signature: 'Hovering a text link reveals a floating image preview tied to the item.',
    interaction: 'Preview follows or anchors near the link with layered motion and fade.',
    usage: 'Use for portfolios, menus, properties, recipes, resources, or editorial indexes.',
    fallback: 'Use CSS hover/focus popovers and static thumbnails when motion is unavailable.',
    mobile: 'Show thumbnails inline because hover is unavailable.',
    mobileGuard: 'Ensure focus users receive the same preview context.',
  }),
  buildVanguardPattern({
    id: 'glass-checkout-card',
    title: 'Glass Checkout Card',
    sourcePromptName: 'Glass Checkout Card',
    category: 'checkout-surface',
    screenTypes: ['form', 'wizard', 'detail'],
    intentTerms: ['checkout', 'payment', 'cart', 'order', 'summary', 'billing'],
    dependencies: ['lucide-react'],
    componentPath: '/components/ui/glass-checkout-card.tsx',
    signature: 'Checkout combines cart summary, payment form, trust cues, and total in a premium surface.',
    interaction: 'Field focus, validation, and pay action make progress obvious.',
    usage: 'Use for product checkout, bookings, subscriptions, invoices, or deposit flows.',
    fallback: 'Use accessible form fields, a sticky summary, and solid contrast if glass is unavailable.',
    mobile: 'Move order summary above payment or into a collapsible section.',
    mobileGuard: 'Keep total and primary pay action visible without crowding fields.',
  }),
  buildVanguardPattern({
    id: 'pricing-card-selector',
    title: 'Pricing Card Selector',
    sourcePromptName: 'Pricing Card Selector',
    category: 'pricing-selection',
    screenTypes: ['landing', 'form', 'wizard'],
    intentTerms: ['pricing', 'plan', 'selector', 'billing', 'subscription', 'package'],
    dependencies: ['framer-motion', 'lucide-react'],
    componentPath: '/components/ui/pricing-card-selector.tsx',
    signature: 'Plans become selectable controls with benefits, price, cadence, and current selection.',
    interaction: 'Selecting a plan animates border, check, and summary without hiding details.',
    usage: 'Use for subscriptions, packages, memberships, delivery plans, or SaaS tiers.',
    fallback: 'Use radio groups inside semantic cards with CSS transitions.',
    mobile: 'Stack plans and keep the selected plan summary close to the CTA.',
    mobileGuard: 'Avoid tiny comparison tables below 390px; prioritize core differences.',
  }),
  buildVanguardPattern({
    id: 'liquid-metal-button',
    title: 'Liquid Metal Button',
    sourcePromptName: 'Liquid Metal Button',
    category: 'premium-action',
    screenTypes: ['landing', 'detail', 'form'],
    intentTerms: ['liquid', 'metal', 'button', 'cta', 'premium', 'shine', 'launch'],
    dependencies: ['framer-motion'],
    componentPath: '/components/ui/liquid-metal-button.tsx',
    signature: 'A primary action feels premium through metallic sheen, fluid highlight, and precise press states.',
    interaction: 'Pointer movement or hover shifts the specular highlight.',
    usage: 'Use sparingly for hero CTAs, purchase, launch, reserve, or unlock actions.',
    fallback: 'Use CSS radial gradients, pseudo-elements, and press transforms.',
    mobile: 'Keep sheen subtle and button height stable.',
    mobileGuard: 'Maintain contrast and avoid animated glare over the label.',
  }),
  buildVanguardPattern({
    id: 'heart-favorite',
    title: 'Heart Favorite Microinteraction',
    sourcePromptName: 'Heart Favorite',
    category: 'micro-action',
    screenTypes: ['list', 'detail', 'dashboard'],
    intentTerms: ['heart', 'favorite', 'like', 'save', 'wishlist', 'reaction'],
    dependencies: ['framer-motion', 'lucide-react'],
    componentPath: '/components/ui/heart-favorite.tsx',
    signature: 'A favorite action gives visible emotional feedback without hijacking the layout.',
    interaction: 'The heart fills, scales, and settles with a crisp state transition.',
    usage: 'Use for products, posts, recipes, listings, properties, or saved searches.',
    fallback: 'Use CSS scale and fill transitions on a button with aria-pressed.',
    mobile: 'Use at least 40px touch target on image/list cards.',
    mobileGuard: 'Keep state readable for both filled and outline variants.',
  }),
  buildVanguardPattern({
    id: 'animated-checkbox',
    title: 'Animated Checkbox',
    sourcePromptName: 'Animated Checkbox',
    category: 'form-control-motion',
    screenTypes: ['form', 'wizard', 'dashboard'],
    intentTerms: ['checkbox', 'check', 'task', 'todo', 'selection', 'agreement'],
    dependencies: ['framer-motion', 'lucide-react'],
    componentPath: '/components/ui/animated-checkbox.tsx',
    signature: 'Checkbox state changes draw a checkmark or fill animation instead of a default snap.',
    interaction: 'Focus, disabled, checked, and indeterminate states remain accessible.',
    usage: 'Use for task lists, agreements, filters, permissions, or onboarding steps.',
    fallback: 'Use native checkbox with custom CSS and an inline SVG check path.',
    mobile: 'Increase row hit area and keep labels tappable.',
    mobileGuard: 'Long labels must wrap without separating from the checkbox.',
  }),
  buildVanguardPattern({
    id: 'highlighted-text',
    title: 'Highlighted Text Emphasis',
    sourcePromptName: 'Highlighted Text',
    category: 'copy-emphasis',
    screenTypes: ['landing', 'detail', 'form', 'wizard'],
    intentTerms: ['highlight', 'text', 'emphasis', 'copy', 'headline', 'label'],
    dependencies: [],
    componentPath: '/components/ui/highlighted-text.tsx',
    signature: 'A highlighted phrase directs attention inside otherwise restrained copy.',
    interaction: 'Highlight may animate on entrance or remain as a static editorial mark.',
    usage: 'Use for value props, feature callouts, onboarding copy, or empty states.',
    fallback: 'Use semantic mark/span with CSS gradients or background-size animation.',
    mobile: 'Allow highlighted phrases to wrap naturally.',
    mobileGuard: 'Avoid highlight colors that reduce text contrast.',
  }),
  buildVanguardPattern({
    id: 'color-selector',
    title: 'Color Selector Swatches',
    sourcePromptName: 'Color Selector',
    category: 'visual-picker-control',
    screenTypes: ['form', 'dashboard', 'wizard', 'detail'],
    intentTerms: ['color', 'selector', 'swatch', 'theme', 'picker', 'customize'],
    dependencies: ['framer-motion'],
    componentPath: '/components/ui/color-selector.tsx',
    signature: 'Color choices are shown as physical swatches with selected and unavailable states.',
    interaction: 'Selection animates ring, check, or active chip without changing layout.',
    usage: 'Use for products, themes, labels, categories, or personalization.',
    fallback: 'Use radio inputs styled as swatches with visible labels.',
    mobile: 'Use wrapping swatch grids with 44px hit areas.',
    mobileGuard: 'Provide text labels or tooltips for color-only choices.',
  }),
  buildVanguardPattern({
    id: 'expanding-search-dock',
    title: 'Expanding Search Dock',
    sourcePromptName: 'Expanding Search Dock',
    category: 'search-command',
    screenTypes: ['dashboard', 'list', 'landing'],
    intentTerms: ['search', 'dock', 'expand', 'command', 'filter', 'input'],
    dependencies: ['framer-motion', 'lucide-react'],
    componentPath: '/components/ui/expanding-search-dock.tsx',
    signature: 'Search starts compact, expands with focus, and becomes a command surface.',
    interaction: 'Focus, clear, submit, and suggestions feel intentional.',
    usage: 'Use for dashboards, catalogs, help centers, command bars, or global search.',
    fallback: 'Use CSS width transitions and native input events.',
    mobile: 'Expand to full width or a top sheet on focus.',
    mobileGuard: 'Prevent focused search from squeezing adjacent controls.',
  }),
  buildVanguardPattern({
    id: 'gallery-grid-lightbox',
    title: 'Gallery Grid Lightbox',
    sourcePromptName: 'Gallery Grid Lightbox',
    category: 'media-gallery',
    screenTypes: ['landing', 'detail', 'list'],
    intentTerms: ['gallery', 'grid', 'lightbox', 'photos', 'images', 'portfolio'],
    dependencies: ['framer-motion', 'lucide-react'],
    componentPath: '/components/ui/gallery-grid-lightbox.tsx',
    signature: 'A media grid opens into a focused lightbox with navigation and image metadata.',
    interaction: 'Click, keyboard, and swipe states respect the media browsing task.',
    usage: 'Use for portfolios, venues, products, rooms, recipes, trips, or case studies.',
    fallback: 'Use CSS grid and a dialog/lightbox with native buttons.',
    mobile: 'Use two-column grids and full-screen lightbox.',
    mobileGuard: 'Keep close/next controls reachable and visible over varied images.',
  }),
  buildVanguardPattern({
    id: 'gradient-wave-text',
    title: 'Gradient Wave Text',
    sourcePromptName: 'Gradient Wave Text',
    category: 'text-motion',
    screenTypes: ['landing', 'detail', 'chat'],
    intentTerms: ['gradient', 'wave', 'text', 'headline', 'shimmer', 'loading'],
    dependencies: ['framer-motion'],
    componentPath: '/components/ui/gradient-wave-text.tsx',
    signature: 'A gradient wave travels across headline text to imply energy or generation.',
    interaction: 'The wave is timed and limited so the text remains readable.',
    usage: 'Use for AI generation, loading labels, premium headlines, or state transitions.',
    fallback: 'Use CSS background-position keyframes on clipped text.',
    mobile: 'Keep line length short and use stable font sizing.',
    mobileGuard: 'Do not rely on transparent text without a fallback color.',
  }),
  buildVanguardPattern({
    id: 'bars-spinner',
    title: 'Bars Spinner',
    sourcePromptName: 'Bars Spinner',
    category: 'loading-state',
    screenTypes: ['form', 'dashboard', 'chat', 'wizard'],
    intentTerms: ['spinner', 'loading', 'bars', 'progress', 'wait', 'processing'],
    dependencies: [],
    componentPath: '/components/ui/bars-spinner.tsx',
    signature: 'A compact bars loader communicates activity without taking over the surface.',
    interaction: 'Bars animate in rhythm and can sit inline with labels.',
    usage: 'Use for buttons, cards, chat, saves, uploads, or small pending states.',
    fallback: 'Use pure CSS keyframes and respect prefers-reduced-motion.',
    mobile: 'Keep loader size proportional to its containing control.',
    mobileGuard: 'Pair with accessible status text when work takes longer than a moment.',
  }),
  buildVanguardPattern({
    id: 'glass-listen-app',
    title: 'Glass Listen App',
    sourcePromptName: 'Glass Listen App',
    category: 'media-app-surface',
    screenTypes: ['dashboard', 'detail'],
    intentTerms: ['listen', 'audio', 'music', 'podcast', 'player', 'glass', 'media'],
    dependencies: ['lucide-react', 'framer-motion'],
    componentPath: '/components/ui/glass-listen-app.tsx',
    signature: 'A media player surface combines artwork, queue, controls, and glass depth.',
    interaction: 'Playback controls, progress, and queue selection feel integrated.',
    usage: 'Use for audio apps, lessons, voice notes, meditation, or podcast dashboards.',
    fallback: 'Use native audio controls plus custom surrounding layout where needed.',
    mobile: 'Prioritize artwork, title, and transport controls in one column.',
    mobileGuard: 'Keep progress and controls reachable without covering the queue.',
  }),
  buildVanguardPattern({
    id: 'squiggly-underline',
    title: 'Squiggly Underline',
    sourcePromptName: 'Squiggly Underline',
    category: 'copy-emphasis-motion',
    screenTypes: ['landing', 'detail', 'form'],
    intentTerms: ['squiggly', 'underline', 'text', 'highlight', 'emphasis', 'link'],
    dependencies: [],
    componentPath: '/components/ui/squiggly-underline.tsx',
    signature: 'A hand-drawn underline adds human emphasis to a key word or link.',
    interaction: 'Underline can draw in on view or hover while staying readable.',
    usage: 'Use for one promise, important link, creator note, or editorial phrase.',
    fallback: 'Use SVG background-image, border-image, or CSS mask underline.',
    mobile: 'Allow underline to break gracefully across wrapped words.',
    mobileGuard: 'Do not decorate every link; reserve it for the most important phrase.',
  }),
  buildVanguardPattern({
    id: 'notification-popover',
    title: 'Notification Popover',
    sourcePromptName: 'Notification Popover',
    category: 'popover-feed',
    screenTypes: ['dashboard', 'list', 'chat'],
    intentTerms: ['notification', 'popover', 'alerts', 'feed', 'bell', 'inbox'],
    dependencies: ['lucide-react', '@radix-ui/react-popover'],
    componentPath: '/components/ui/notification-popover.tsx',
    signature: 'Notifications open into a compact actionable feed with unread state and grouping.',
    interaction: 'Bell, count, read state, and row actions create a real product workflow.',
    usage: 'Use for alerts, messages, order updates, build events, or collaboration feeds.',
    fallback: 'Use a button plus absolutely positioned panel with focus trapping where possible.',
    mobile: 'Convert popover to a sheet or full-width panel.',
    mobileGuard: 'Keep close and mark-read actions accessible by keyboard and touch.',
  }),
  buildVanguardPattern({
    id: 'magnified-bento',
    title: 'Magnified Bento',
    sourcePromptName: 'Magnified Bento',
    category: 'interactive-bento',
    screenTypes: ['dashboard', 'landing', 'detail'],
    intentTerms: ['magnified', 'bento', 'hover', 'feature', 'cards', 'zoom'],
    dependencies: ['framer-motion'],
    componentPath: '/components/ui/magnified-bento.tsx',
    signature: 'A bento grid magnifies the active module while preserving the overall system map.',
    interaction: 'Hover/focus expands one panel and compresses adjacent context smoothly.',
    usage: 'Use for product feature maps, analytics summaries, editor toolsets, or service menus.',
    fallback: 'Use CSS grid-template transitions or static active cards.',
    mobile: 'Use tap-to-expand accordions instead of hover magnification.',
    mobileGuard: 'Expanded cards must not push essential actions out of reach.',
  }),
  buildVanguardPattern({
    id: 'bottom-menu',
    title: 'Bottom Mobile Menu',
    sourcePromptName: 'Bottom Menu',
    category: 'mobile-navigation',
    screenTypes: ['dashboard', 'list', 'detail', 'chat'],
    intentTerms: ['bottom', 'menu', 'mobile', 'navigation', 'tabs', 'dock'],
    dependencies: ['lucide-react', 'framer-motion'],
    componentPath: '/components/ui/bottom-menu.tsx',
    signature: 'A mobile bottom dock exposes the most important app destinations with icon clarity.',
    interaction: 'Active item, tap feedback, badges, and safe-area padding are deliberate.',
    usage: 'Use for mobile-first apps, marketplaces, chat, dashboards, or member portals.',
    fallback: 'Use fixed nav with semantic links and CSS active states.',
    mobile: 'Respect safe-area-inset-bottom and keep labels short.',
    mobileGuard: 'Do not cover page CTAs or form submit controls without adding bottom padding.',
  }),
  buildVanguardPattern({
    id: 'date-wheel-picker',
    title: 'Date Wheel Picker',
    sourcePromptName: 'Date Wheel Picker',
    category: 'date-time-control',
    screenTypes: ['form', 'wizard', 'dashboard'],
    intentTerms: ['date', 'wheel', 'picker', 'calendar', 'schedule', 'time'],
    dependencies: ['framer-motion', 'lucide-react'],
    componentPath: '/components/ui/date-wheel-picker.tsx',
    signature: 'Date selection uses tactile wheel columns for day, month, time, or schedule slots.',
    interaction: 'Scroll snap, selected row emphasis, and confirm action make the picker feel native.',
    usage: 'Use for bookings, delivery windows, reminders, appointments, or scheduling.',
    fallback: 'Use native date/time inputs with styled summary chips when wheel logic is unavailable.',
    mobile: 'Use full-width wheel columns and large row heights.',
    mobileGuard: 'Always provide typed or native fallback for accessibility.',
  }),
  buildVanguardPattern({
    id: 'floating-chat-widget',
    title: 'Floating Chat Widget',
    sourcePromptName: 'Floating Chat Widget',
    category: 'chat-surface',
    screenTypes: ['chat', 'landing', 'dashboard'],
    intentTerms: ['chat', 'widget', 'floating', 'support', 'assistant', 'message'],
    dependencies: ['framer-motion', 'lucide-react'],
    componentPath: '/components/ui/floating-chat-widget.tsx',
    signature: 'A floating chat launcher expands into a compact support or assistant conversation.',
    interaction: 'Open, close, unread, typing, and send states are animated but practical.',
    usage: 'Use for AI assistants, support, sales intake, concierge, or WhatsApp-like contact.',
    fallback: 'Use fixed button plus dialog/panel with CSS transitions.',
    mobile: 'Open as a bottom sheet or full-screen chat.',
    mobileGuard: 'Keep input above keyboard and preserve scroll position.',
  }),
  buildVanguardPattern({
    id: 'perspective-book',
    title: 'Perspective Book',
    sourcePromptName: 'Perspective Book',
    category: '3d-object-showcase',
    screenTypes: ['landing', 'detail'],
    intentTerms: ['book', 'perspective', 'cover', 'ebook', 'guide', '3d', 'mockup'],
    dependencies: ['framer-motion'],
    componentPath: '/components/ui/perspective-book.tsx',
    signature: 'A book or guide cover is shown as a tasteful 3D object with depth and shadow.',
    interaction: 'Hover or entrance tilts the object while preserving cover legibility.',
    usage: 'Use for guides, courses, reports, menus, notebooks, or premium downloads.',
    fallback: 'Use CSS transform perspective and box-shadow without motion dependencies.',
    mobile: 'Reduce tilt and keep the cover centered.',
    mobileGuard: 'Avoid tiny cover text that cannot be read on mobile.',
  }),
  buildVanguardPattern({
    id: 'animated-collection',
    title: 'Animated Collection',
    sourcePromptName: 'Animated Collection',
    category: 'collection-grid-motion',
    screenTypes: ['list', 'landing', 'detail'],
    intentTerms: ['collection', 'gallery', 'cards', 'products', 'items', 'animated'],
    dependencies: ['framer-motion'],
    componentPath: '/components/ui/animated-collection.tsx',
    signature: 'A collection of items enters and reorders with staggered motion and clear item hierarchy.',
    interaction: 'Filtering, selection, or reveal states animate without losing orientation.',
    usage: 'Use for products, recipes, projects, courses, files, or saved items.',
    fallback: 'Use CSS grid and transition delays for reveal states.',
    mobile: 'Use two-column or one-column layouts based on item complexity.',
    mobileGuard: 'Keep item actions visible and avoid hover-only controls.',
  }),
  buildVanguardPattern({
    id: 'cards-slider',
    title: 'Cards Slider',
    sourcePromptName: 'Cards Slider',
    category: 'carousel-cards',
    screenTypes: ['landing', 'list', 'detail'],
    intentTerms: ['cards', 'slider', 'carousel', 'testimonials', 'products', 'features'],
    dependencies: ['framer-motion', 'lucide-react'],
    componentPath: '/components/ui/cards-slider.tsx',
    signature: 'Cards slide through a focused viewport with clear previous/next affordances.',
    interaction: 'Drag, button, keyboard, and pagination states are coordinated.',
    usage: 'Use for testimonials, products, features, team members, plans, or case studies.',
    fallback: 'Use CSS scroll-snap with buttons and accessible labels.',
    mobile: 'Use native horizontal scrolling with snap points.',
    mobileGuard: 'Ensure partially visible cards do not create horizontal page overflow.',
  }),
  buildVanguardPattern({
    id: 'filter-list-item',
    title: 'Filter List Item',
    sourcePromptName: 'List Item',
    category: 'filter-selection-list',
    screenTypes: ['list', 'dashboard', 'form'],
    intentTerms: ['filter', 'list', 'item', 'tasks', 'events', 'reminders', 'selection'],
    dependencies: ['motion', 'clsx', '@hugeicons/react', '@hugeicons/core-free-icons'],
    componentPath: '/components/ui/list-item.tsx',
    signature: 'A filter picker opens into animated rows with icon identity and selected check state.',
    interaction: 'Rows stagger in and close after selection to make the control feel deliberate.',
    usage: 'Use for task filters, calendars, categories, tags, inbox views, or dashboards.',
    fallback: 'Use CSS transitions and lucide icons when hugeicons or motion/react is unavailable.',
    mobile: 'Open as a centered popover or bottom sheet with large rows.',
    mobileGuard: 'Keep selected state visible without relying only on color.',
  }),
  buildVanguardPattern({
    id: 'stacked-list',
    title: 'Stacked Member List',
    sourcePromptName: 'Stacked List X',
    category: 'people-list',
    screenTypes: ['list', 'dashboard'],
    intentTerms: ['stacked', 'members', 'team', 'search', 'role', 'avatars', 'list'],
    dependencies: ['motion', '@hugeicons/react', '@hugeicons/core-free-icons'],
    componentPath: '/components/ui/stacked-list.tsx',
    signature: 'A member list stacks rows with avatar, online state, role badges, search, and add controls.',
    interaction: 'Filtering and row entrance use motion while keeping the list operational.',
    usage: 'Use for teams, assignees, participants, CRM contacts, or project rosters.',
    fallback: 'Use CSS row transitions and lucide icons when motion/hugeicons are unavailable.',
    mobile: 'Use compact role badges and preserve avatar/name/status priority.',
    mobileGuard: 'Long role labels must truncate without hiding member identity.',
  }),
  buildVanguardPattern({
    id: 'avatar-badge',
    title: 'Avatar Badge',
    sourcePromptName: 'Avatar Badge',
    category: 'identity-status',
    screenTypes: ['dashboard', 'list', 'chat', 'detail'],
    intentTerms: ['avatar', 'badge', 'status', 'online', 'profile', 'user'],
    dependencies: ['@radix-ui/react-avatar', 'lucide-react'],
    componentPath: '/components/ui/avatar-badge.tsx',
    signature: 'An avatar carries status or role information as a small readable badge.',
    interaction: 'Hover/focus can expose status detail without hiding the face/name.',
    usage: 'Use for users, agents, assignees, team members, or chat participants.',
    fallback: 'Use image plus initials fallback and an absolutely positioned status dot.',
    mobile: 'Keep badge large enough to read but smaller than the face area.',
    mobileGuard: 'Provide text status nearby when badge meaning is not obvious.',
  }),
  buildVanguardPattern({
    id: 'social-button',
    title: 'Social Button',
    sourcePromptName: 'Social Button',
    category: 'auth-action',
    screenTypes: ['form', 'landing'],
    intentTerms: ['social', 'button', 'login', 'auth', 'oauth', 'github', 'google'],
    dependencies: ['lucide-react'],
    componentPath: '/components/ui/social-button.tsx',
    signature: 'A social action button clearly identifies provider, state, and expected account flow.',
    interaction: 'Hover, loading, disabled, and connected states are explicit.',
    usage: 'Use for sign-in, connect account, import, OAuth, or integration actions.',
    fallback: 'Use provider text plus lucide/icon fallback if brand SVGs are unavailable.',
    mobile: 'Full-width buttons stack with consistent height.',
    mobileGuard: 'Do not use icon-only social auth without accessible labels.',
  }),
  buildVanguardPattern({
    id: 'team-showcase',
    title: 'Team Showcase',
    sourcePromptName: 'Team Showcase',
    category: 'people-showcase',
    screenTypes: ['landing', 'list', 'detail'],
    intentTerms: ['team', 'showcase', 'people', 'staff', 'experts', 'avatars'],
    dependencies: ['framer-motion', 'lucide-react'],
    componentPath: '/components/ui/team-showcase.tsx',
    signature: 'People are presented as a curated team moment, not a generic card grid.',
    interaction: 'Hover, stagger, or focus reveals role and contribution.',
    usage: 'Use for agencies, clinics, education, services, creators, or company pages.',
    fallback: 'Use CSS grid with image cards and focus-visible overlays.',
    mobile: 'Stack or carousel team members depending on count.',
    mobileGuard: 'Keep names and roles readable over photos with contrast protection.',
  }),
  buildVanguardPattern({
    id: 'animated-tooltip',
    title: 'Animated Tooltip',
    sourcePromptName: 'Animated Tooltip',
    category: 'micro-help',
    screenTypes: ['dashboard', 'form', 'list', 'detail'],
    intentTerms: ['tooltip', 'hint', 'hover', 'help', 'label', 'info'],
    dependencies: ['framer-motion', '@radix-ui/react-tooltip'],
    componentPath: '/components/ui/animated-tooltip.tsx',
    signature: 'Tooltips appear with precise motion and explain icon-only controls without clutter.',
    interaction: 'Delay, escape, focus, and hover behavior match accessible expectations.',
    usage: 'Use for toolbars, dense dashboards, icon buttons, charts, and settings.',
    fallback: 'Use native title sparingly or CSS/ARIA tooltip primitives.',
    mobile: 'Avoid hover-only help; provide tap or inline labels for critical actions.',
    mobileGuard: 'Tooltip content must not overflow the viewport.',
  }),
  buildVanguardPattern({
    id: 'basic-circle-text',
    title: 'Circle Text Badge',
    sourcePromptName: 'Basic Circle Text',
    category: 'decorative-label',
    screenTypes: ['landing', 'detail'],
    intentTerms: ['circle', 'text', 'badge', 'stamp', 'label', 'rotating'],
    dependencies: ['framer-motion'],
    componentPath: '/components/ui/basic-circle-text.tsx',
    signature: 'Circular text creates a stamp-like proof or brand accent.',
    interaction: 'Rotation or reveal is subtle and secondary to the main content.',
    usage: 'Use for awards, local badges, handmade cues, verified status, or campaign marks.',
    fallback: 'Use SVG textPath or static circular text image when motion is unavailable.',
    mobile: 'Shrink or hide decorative circle if it competes with CTA.',
    mobileGuard: 'Never place essential copy only in circular text.',
  }),
  buildVanguardPattern({
    id: 'area-chart',
    title: 'Area Chart',
    sourcePromptName: 'Area Chart',
    category: 'data-visualization',
    screenTypes: ['dashboard', 'detail'],
    intentTerms: ['area', 'chart', 'analytics', 'trend', 'revenue', 'metrics', 'visx'],
    dependencies: ['@visx/shape', '@visx/scale', '@visx/group', '@visx/axis'],
    componentPath: '/components/ui/area-chart.tsx',
    signature: 'An area chart shows trend, magnitude, and time context with production-grade axes.',
    interaction: 'Tooltips, active points, and labels connect data to decisions.',
    usage: 'Use for revenue, orders, usage, traffic, retention, or operational metrics.',
    fallback: 'Use SVG path generation or CSS-friendly sparkline if visx is unavailable.',
    mobile: 'Reduce axis density and keep touch tooltip targets large.',
    mobileGuard: 'Do not let chart labels collide or overflow the card.',
  }),
  buildVanguardPattern({
    id: 'animated-push-list',
    title: 'Animated Push List',
    sourcePromptName: 'Animated Push List',
    category: 'live-list',
    screenTypes: ['dashboard', 'list', 'chat'],
    intentTerms: ['push', 'list', 'notifications', 'activity', 'feed', 'live', 'queue'],
    dependencies: ['framer-motion', 'lucide-react'],
    componentPath: '/components/ui/animated-push-list.tsx',
    signature: 'New items push into a list with visible ordering and live activity rhythm.',
    interaction: 'Insertions, removals, and status changes animate without disorienting the user.',
    usage: 'Use for activity feeds, build logs, orders, messages, notifications, or queues.',
    fallback: 'Use CSS transitions and stable keys for entry/exit states.',
    mobile: 'Keep row height compact and action buttons reachable.',
    mobileGuard: 'Avoid auto-scrolling away from user focus unless clearly requested.',
  }),
  buildVanguardPattern({
    id: 'accordion-space',
    title: 'Accordion Space',
    sourcePromptName: 'Accordion Space',
    category: 'disclosure-content',
    screenTypes: ['landing', 'detail', 'form', 'wizard'],
    intentTerms: ['accordion', 'faq', 'space', 'collapsible', 'content', 'questions'],
    dependencies: ['@radix-ui/react-accordion', '@radix-ui/react-icons'],
    componentPath: '/components/ui/accordion-space.tsx',
    signature: 'Accordion items open with enough breathing room and icon motion to feel crafted.',
    interaction: 'Chevron rotation, height animation, and readable content density are coordinated.',
    usage: 'Use for FAQs, settings sections, policies, product details, or onboarding help.',
    fallback: 'Use details/summary with CSS transitions where Radix is unavailable.',
    mobile: 'Use full-width triggers with generous tap targets.',
    mobileGuard: 'Long answer content must wrap and remain readable.',
  }),
  buildVanguardPattern({
    id: 'radio-group-dashed',
    title: 'Dashed Radio Group',
    sourcePromptName: 'Radio Grouped Dashed',
    category: 'choice-control',
    screenTypes: ['form', 'wizard', 'detail'],
    intentTerms: ['radio', 'group', 'dashed', 'shipping', 'choice', 'option'],
    dependencies: ['@radix-ui/react-radio-group', '@radix-ui/react-label', 'lucide-react'],
    componentPath: '/components/ui/radio-group-dashed-demo.tsx',
    signature: 'Radio choices get a playful dashed selection treatment while staying semantic.',
    interaction: 'Focus, checked, and disabled states are clear in the control and label.',
    usage: 'Use for shipping methods, plan choices, preferences, filters, or setup options.',
    fallback: 'Use native radio inputs with styled labels and visible checked state.',
    mobile: 'Stack options vertically and keep labels tappable.',
    mobileGuard: 'Do not let custom border styles obscure checked state contrast.',
  }),
  buildVanguardPattern({
    id: 'animated-loading-breadcrumb',
    title: 'Animated Loading Breadcrumb',
    sourcePromptName: 'Animated Loader',
    category: 'loading-state-branded',
    screenTypes: ['dashboard', 'chat', 'wizard', 'form'],
    intentTerms: ['loading', 'loader', 'breadcrumb', 'shimmer', 'processing', 'cooking'],
    dependencies: ['lucide-react'],
    componentPath: '/components/ui/animated-loading-svg-text-shimmer.tsx',
    signature: 'Loading is shown as a drawn SVG path plus shimmer breadcrumb text.',
    interaction: 'The animated stroke and text shimmer communicate active progress without a generic spinner.',
    usage: 'Use for AI generation, uploads, route transitions, processing steps, or app shell loading.',
    fallback: 'Use inline SVG stroke animation and CSS shimmer keyframes with no external dependency beyond icons.',
    mobile: 'Keep the breadcrumb short and centered in its container.',
    mobileGuard: 'Expose role=status and readable loading text for assistive tech.',
  }),
  buildVanguardPattern({
    id: 'animated-state-icons',
    title: 'Animated State Icons',
    sourcePromptName: 'animated state icons',
    category: 'state-icon-system',
    screenTypes: ['dashboard', 'form', 'chat', 'wizard'],
    intentTerms: ['animated', 'icons', 'state', 'success', 'loading', 'toggle', 'copy', 'send'],
    dependencies: ['framer-motion'],
    componentPath: '/components/ui/animated-state-icons.tsx',
    signature: 'Icons morph between meaningful states such as loading to success or play to pause.',
    interaction: 'State transitions tell a micro-story instead of swapping static icons.',
    usage: 'Use for buttons, status panels, onboarding, media controls, uploads, and notifications.',
    fallback: 'Use CSS keyframes or simple SVG path transitions when framer-motion is unavailable.',
    mobile: 'Keep icons sized consistently inside controls.',
    mobileGuard: 'Do not make essential state dependent only on animation timing.',
  }),
  buildVanguardPattern({
    id: 'team-scaling-hero',
    title: 'Team Scaling Hero',
    sourcePromptName: 'Heroz',
    category: 'startup-hero-proof',
    screenTypes: ['landing'],
    intentTerms: ['hero', 'team', 'scale', 'logo', 'cloud', 'header', 'startup'],
    dependencies: ['lucide-react', '@radix-ui/react-slot', 'class-variance-authority', 'framer-motion', 'react-use-measure'],
    componentPath: '/components/ui/hero-1.tsx',
    signature: 'A startup hero combines sticky header, bold headline, dual CTAs, and moving logo proof.',
    interaction: 'Header scroll state, menu toggle, and infinite logo slider create a polished landing shell.',
    usage: 'Use for agencies, hiring platforms, expert networks, SaaS launches, or service firms.',
    fallback: 'Use CSS marquee, native buttons, and simple sticky header when motion/measure libraries are unavailable.',
    mobile: 'Use a real mobile menu and keep CTAs wrapped cleanly.',
    mobileGuard: 'Logo cloud must not overflow or dominate the hero on small screens.',
  }),
  buildVanguardPattern({
    id: 'vercel-style-hero-banner',
    title: 'Vercel Style Business Hero',
    sourcePromptName: 'Vercep Hero',
    category: 'image-hero-with-marquee',
    screenTypes: ['landing'],
    intentTerms: ['hero', 'marquee', 'avatar', 'stats', 'business', 'template', 'revenue'],
    dependencies: ['lucide-react', '@radix-ui/react-avatar'],
    componentPath: '/components/ui/hero.tsx',
    signature: 'A full-bleed business hero overlays avatar proof, stats marquee, and sharp CTA over real imagery.',
    interaction: 'Marquee proof and avatar stack create momentum around the offer.',
    usage: 'Use for agencies, growth offers, consulting, templates, or business services.',
    fallback: 'Use CSS marquee and simple image/avatar primitives if shadcn components are unavailable.',
    mobile: 'Stack headline and supporting copy with safe bottom padding.',
    mobileGuard: 'Ensure background image keeps subject visibility and text contrast.',
  }),
  buildVanguardPattern({
    id: 'kinetic-navigation',
    title: 'Sterling Gate Kinetic Navigation',
    sourcePromptName: 'Kinetic Navigation',
    category: 'navigation-overlay',
    screenTypes: ['landing', 'dashboard'],
    intentTerms: ['kinetic', 'navigation', 'menu', 'overlay', 'gsap', 'nav', 'shapes'],
    dependencies: ['gsap'],
    componentPath: '/components/ui/sterling-gate-kinetic-navigation.tsx',
    signature: 'A fullscreen navigation overlay opens with layered panels and ambient shapes.',
    interaction: 'Menu open/close, text reveal, hover-linked shapes, and escape handling feel intentional.',
    usage: 'Use for portfolio, agency, editorial, brand, or immersive app navigation.',
    fallback: 'Use CSS transitions and keyframes when GSAP is unavailable.',
    mobile: 'Keep menu items large and overlay scroll-safe.',
    mobileGuard: 'Trap focus or provide clear close/escape behavior.',
  }),
  buildVanguardPattern({
    id: 'interactive-thermodynamic-grid',
    title: 'Interactive Thermodynamic Grid',
    sourcePromptName: 'Interactive termodinamic',
    category: 'canvas-background',
    screenTypes: ['landing', 'dashboard', 'detail'],
    intentTerms: ['thermodynamic', 'heat', 'grid', 'canvas', 'interactive', 'background', 'thermal'],
    dependencies: [],
    componentPath: '/components/ui/interactive-thermodynamic-grid.tsx',
    signature: 'A canvas heat grid reacts to pointer movement with thermal trails and simulated energy.',
    interaction: 'Mouse or touch injects heat while cells cool and glow.',
    usage: 'Use for technical products, energy, AI labs, security, analytics, or experimental landing backgrounds.',
    fallback: 'Use a static thermal gradient grid or CSS radial background when canvas is unavailable.',
    mobile: 'Lower resolution and animation cost on touch devices.',
    mobileGuard: 'Keep content layers above the canvas readable and pointer-safe.',
  }),
  buildVanguardPattern({
    id: 'hero-shutter-text',
    title: 'Hero Shutter Text',
    sourcePromptName: 'Hero Stutter effect',
    category: 'headline-motion',
    screenTypes: ['landing', 'detail'],
    intentTerms: ['shutter', 'stutter', 'hero', 'text', 'slice', 'headline', 'glitch'],
    dependencies: ['framer-motion', 'lucide-react'],
    componentPath: '/components/ui/hero-shutter-text.tsx',
    signature: 'Giant typography rebuilds through sliced shutter passes and a manual replay control.',
    interaction: 'Clicking refresh retriggers the visual reveal without changing the page structure.',
    usage: 'Use for bold brand names, launches, campaigns, creative tools, or immersive headers.',
    fallback: 'Use CSS clip-path layers and keyframes when framer-motion is unavailable.',
    mobile: 'Clamp headline size and preserve full word visibility.',
    mobileGuard: 'Do not let decorative controls overlap the headline or safe areas.',
  }),
  buildVanguardPattern({
    id: 'halide-topo-hero',
    title: 'Halide Topographic Hero',
    sourcePromptName: 'Halide Hero',
    category: 'experimental-hero',
    screenTypes: ['landing'],
    intentTerms: ['halide', 'topographic', 'hero', '3d', 'parallax', 'grain', 'archive'],
    dependencies: [],
    componentPath: '/components/ui/halide-topo-hero.tsx',
    signature: 'A monochrome 3D parallax canvas layers images, contours, grain, and interface copy.',
    interaction: 'Mouse movement shifts the scene in depth like an archival optical plate.',
    usage: 'Use for fashion, photography, studios, archives, events, or experimental portfolios.',
    fallback: 'Use CSS transform-style layers and static images with reduced motion fallback.',
    mobile: 'Disable intense parallax and reduce fixed interface padding.',
    mobileGuard: 'Keep CTA and title readable over image layers.',
  }),
  buildVanguardPattern({
    id: 'not-found-empty',
    title: '404 Empty State',
    sourcePromptName: '404',
    category: 'empty-state',
    screenTypes: ['detail', 'landing'],
    intentTerms: ['404', 'not found', 'empty', 'error', 'home', 'explore'],
    dependencies: ['lucide-react', 'class-variance-authority', '@radix-ui/react-slot'],
    componentPath: '/components/ui/not-found-2.tsx',
    signature: 'A 404 page uses an empty-state system with oversized code and clear recovery actions.',
    interaction: 'Primary and secondary buttons guide users back into the product.',
    usage: 'Use for missing routes, deleted records, expired links, or empty sections.',
    fallback: 'Use semantic empty-state markup and native anchor buttons.',
    mobile: 'Scale down 404 type and keep actions stacked or wrapped.',
    mobileGuard: 'Do not use no-wrap copy that clips on small screens.',
  }),
  buildVanguardPattern({
    id: 'agent-loop-infinite-slider',
    title: 'Agent Loop Infinite Slider',
    sourcePromptName: 'Agent Loop Infinite slider',
    category: 'immersive-project-slider',
    screenTypes: ['landing', 'list', 'detail'],
    intentTerms: ['infinite', 'slider', 'projects', 'parallax', 'scroll', 'gallery', 'portfolio'],
    dependencies: [],
    componentPath: '/components/ui/argent-loop-infinite-slider.tsx',
    signature: 'A full-screen infinite project slider snaps through large images with minimap context.',
    interaction: 'Wheel, touch, snapping, parallax, and minimap info stay in sync.',
    usage: 'Use for portfolios, product collections, campaigns, editorial archives, or visual catalogs.',
    fallback: 'Use scroll-snap sections and static minimap labels if custom animation loops are too heavy.',
    mobile: 'Support touch drag and reduce parallax intensity.',
    mobileGuard: 'Prevent wheel listeners from trapping the entire app when embedded.',
  }),
  buildVanguardPattern({
    id: 'story-viewer',
    title: 'Story Viewer',
    sourcePromptName: 'Story Viewer',
    category: 'media-story-ui',
    screenTypes: ['chat', 'dashboard', 'list'],
    intentTerms: ['story', 'viewer', 'stories', 'video', 'image', 'progress', 'avatar'],
    dependencies: ['framer-motion', 'lucide-react'],
    componentPath: '/components/ui/story-viewer.tsx',
    signature: 'Stories appear as segmented avatar rings and open into a full-screen media viewer.',
    interaction: 'Progress bars, tap zones, swipe, pause, mute, and keyboard controls create a real story UX.',
    usage: 'Use for social feeds, updates, training clips, product stories, or customer activity.',
    fallback: 'Use dialog, CSS progress bars, and native video/image elements without motion if needed.',
    mobile: 'Use full-screen modal and thumb-friendly tap zones.',
    mobileGuard: 'Pause/close controls must remain accessible over all media.',
  }),
  buildVanguardPattern({
    id: 'bolt-style-chat',
    title: 'Bolt Style Chat',
    sourcePromptName: 'Bolt Style CHat',
    category: 'ai-chat-hero',
    screenTypes: ['chat', 'landing'],
    intentTerms: ['bolt', 'chat', 'ai', 'prompt', 'build', 'model', 'import'],
    dependencies: ['lucide-react'],
    componentPath: '/components/ui/bolt-style-chat.tsx',
    signature: 'An AI builder prompt surface combines ray background, model selector, attachments, and build CTA.',
    interaction: 'Textarea autosize, model menu, import actions, and send state feel production-ready.',
    usage: 'Use for AI app builders, prompt consoles, coding agents, generation tools, or onboarding chat.',
    fallback: 'Use native textarea, menus, and CSS ray background if no component library is available.',
    mobile: 'Keep the prompt box within viewport and collapse secondary controls.',
    mobileGuard: 'Textarea must not overlap import buttons or bottom safe area.',
  }),
  buildVanguardPattern({
    id: 'hero-dithering-card',
    title: 'Hero Dithering CTA',
    sourcePromptName: 'Hero Dithering',
    category: 'shader-cta',
    screenTypes: ['landing', 'detail'],
    intentTerms: ['dithering', 'shader', 'cta', 'hero', 'writing', 'paper', 'noise'],
    dependencies: ['lucide-react', '@paper-design/shaders-react'],
    componentPath: '/components/ui/hero-dithering-card.tsx',
    signature: 'A large CTA panel uses dithered shader motion as texture behind editorial copy.',
    interaction: 'Hover changes shader speed while CTA remains clear and stable.',
    usage: 'Use for writing tools, creative SaaS, AI generation, launch CTAs, or premium signup sections.',
    fallback: 'Use CSS noise, radial gradients, or static dither texture if shader package is unavailable.',
    mobile: 'Reduce border radius, height, and shader opacity.',
    mobileGuard: 'Do not let shader contrast reduce headline readability.',
  }),
  buildVanguardPattern({
    id: 'material-ripple',
    title: 'Material Design Ripple',
    sourcePromptName: 'Design Ripple',
    category: 'surface-interaction',
    screenTypes: ['dashboard', 'form', 'detail', 'landing'],
    intentTerms: ['ripple', 'material', 'press', 'button', 'surface', 'interactive'],
    dependencies: ['lucide-react'],
    componentPath: '/components/ui/material-design-3-ripple.tsx',
    signature: 'Press feedback radiates from pointer origin with Material-like timing and soft edges.',
    interaction: 'Hover, touch delay, hold, click, and release states all produce tactile feedback.',
    usage: 'Use on important buttons, cards, security surfaces, media controls, or high-touch panels.',
    fallback: 'Use CSS pseudo-elements and pointer coordinates where Web Animations API is unavailable.',
    mobile: 'Respect touch delay and minimum press duration without feeling laggy.',
    mobileGuard: 'Ripple must not intercept child control clicks or hide labels.',
  }),
  buildVanguardPattern({
    id: 'responsive-hero-banner',
    title: 'Responsive Space Hero Banner',
    sourcePromptName: 'Responsive Hero Banner',
    category: 'image-hero-navigation',
    screenTypes: ['landing'],
    intentTerms: ['responsive', 'hero', 'banner', 'space', 'nav', 'partners', 'mars'],
    dependencies: [],
    componentPath: '/components/ui/responsive-hero-banner.tsx',
    signature: 'A full-bleed background image hero pairs navigation, badge, CTAs, and partner proof.',
    interaction: 'Mobile menu, badge reveal, and CTA affordances support a complete landing shell.',
    usage: 'Use for travel, events, services, products, venues, or image-led campaigns.',
    fallback: 'Use semantic header/nav, static partner logos, and CSS animation utilities.',
    mobile: 'Use a real menu button and stack CTAs below concise hero copy.',
    mobileGuard: 'Partner logos must wrap without shrinking into illegibility.',
  }),
  buildVanguardPattern({
    id: 'member-selector',
    title: 'Member Selector',
    sourcePromptName: 'Member selector',
    category: 'people-picker',
    screenTypes: ['form', 'dashboard', 'chat', 'wizard'],
    intentTerms: ['member', 'selector', 'participants', 'team', 'avatar', 'people', 'search'],
    dependencies: ['framer-motion', 'lucide-react'],
    componentPath: '/components/ui/member-selector.tsx',
    signature: 'Selected people appear as avatars while an add control opens searchable member selection.',
    interaction: 'Avatar selection, dropdown search, selected checks, and max limits are explicit.',
    usage: 'Use for participants, assignees, sharing, project teams, chats, or scheduling.',
    fallback: 'Use native buttons, input filtering, and static avatar initials if motion is unavailable.',
    mobile: 'Open the member list as a full-width popover or sheet.',
    mobileGuard: 'Keep avatar labels short and prevent dropdown overflow.',
  }),
];

function normalize(value: string) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim();
}

function tokenize(value: string) {
  return new Set(normalize(value).split(/\s+/).filter((part) => part.length >= 3));
}

function scorePattern(
  pattern: RetrobuilderVanguardPattern,
  node: Pick<SpecularNodeInput, 'label' | 'description' | 'type'> & Partial<Pick<SpecularNodeInput, 'data_contract' | 'acceptance_criteria' | 'error_handling'>>,
  screenType: SpecularScreenType,
) {
  const nodeText = [
    node.label,
    node.description || '',
    node.type || '',
    screenType,
    node.data_contract || '',
    ...(node.acceptance_criteria || []),
    ...(node.error_handling || []),
  ].join(' ');
  const nodeTokens = tokenize(nodeText);
  const patternTokens = tokenize([
    pattern.id,
    pattern.title,
    pattern.category,
    pattern.sourcePromptName,
    pattern.intentTerms.join(' '),
    pattern.designDna.join(' '),
    pattern.implementationNotes.join(' '),
    pattern.screenTypes.join(' '),
  ].join(' '));
  let score = pattern.screenTypes.includes(screenType) ? 42 : 16;

  for (const token of nodeTokens) {
    if (patternTokens.has(token)) score += 8;
  }
  for (const term of pattern.intentTerms) {
    if (normalize(nodeText).includes(term)) score += 10;
  }
  if (pattern.dependencies.length > 0) score += 4;
  if (pattern.componentPath) score += 3;
  return score;
}

function toReferenceCandidate(
  pattern: RetrobuilderVanguardPattern,
  score: number,
  node: Pick<SpecularNodeInput, 'id' | 'label'>,
): SpecularReferenceCandidate {
  return {
    id: `vanguard-${pattern.id}`,
    title: pattern.title,
    category: pattern.category,
    rationale: [
      `${pattern.sourcePromptName} pattern adapted for ${node.label}.`,
      `Design DNA: ${pattern.designDna.join(' ')}`,
      `Translation rule: ${pattern.implementationNotes[0]}`,
    ].join(' '),
    tags: [pattern.id, pattern.category, pattern.sourcePromptName, ...pattern.intentTerms].slice(0, 16),
    source: 'retrobuilder-vanguard',
    patternId: pattern.id,
    sourcePromptName: pattern.sourcePromptName,
    dependencies: pattern.dependencies,
    componentKey: pattern.componentPath,
    stackAdapters: pattern.stackAdapters,
    implementationNotes: pattern.implementationNotes,
    mobileRules: pattern.mobileRules,
    tasteScore: score,
  };
}

export function getVanguardPatternReferenceCandidates(
  node: Pick<SpecularNodeInput, 'id' | 'label' | 'description' | 'type'> & Partial<Pick<SpecularNodeInput, 'data_contract' | 'acceptance_criteria' | 'error_handling'>>,
  screenType: SpecularScreenType,
  limit = 4,
): SpecularReferenceCandidate[] {
  return RETROBUILDER_VANGUARD_PATTERNS
    .map((pattern) => ({ pattern, score: scorePattern(pattern, node, screenType) }))
    .sort((a, b) => b.score - a.score || a.pattern.title.localeCompare(b.pattern.title))
    .slice(0, limit)
    .map(({ pattern, score }) => toReferenceCandidate(pattern, score, node));
}

export function getVanguardPatternById(patternId: string | undefined) {
  if (!patternId) return undefined;
  return RETROBUILDER_VANGUARD_PATTERNS.find((pattern) => pattern.id === patternId);
}

export function summarizeVanguardReference(reference: SpecularReferenceCandidate) {
  if (reference.source !== 'retrobuilder-vanguard') return '';
  const adapters = Object.keys(reference.stackAdapters || {}).join(', ');
  return [
    `${reference.title} (${reference.patternId || reference.id})`,
    reference.dependencies?.length ? `deps: ${reference.dependencies.join(', ')}` : 'deps: none',
    adapters ? `stack adapters: ${adapters}` : '',
    reference.implementationNotes?.length ? `notes: ${reference.implementationNotes.slice(0, 2).join(' ')}` : '',
    reference.mobileRules?.length ? `mobile: ${reference.mobileRules.slice(0, 2).join(' ')}` : '',
  ].filter(Boolean).join(' | ');
}
